layout_spectrum: 0.394768437060463
typography_spectrum: 0.17329399181271693
color:
  saturation: 0.8329952445846641
  brandStrength: 0.3674536238340569
  lightness: 0.25984712979193814
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  rhythmicContrast: 0.43352986456623466
title: Chica
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/4a7193a6eced56967aca3da6ee8f86295e64144d.jpg">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/4a7193a6eced56967aca3da6ee8f86295e64144d.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: imgflo.herokuapp.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      isBasedOnUrl: >-
        https://imgflo.herokuapp.com/graph/2b2431f8e7ba7b0/bcb3629bc000cb7d32a119bd10037e25/noop.jpg?input=https%3A%2F%2Fcdn.pixabay.com%2Fphoto%2F2016%2F05%2F20%2F21%2F05%2Ffacade-1405964__340.jpg
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Transforming the Narrative
navigation:
  - name: Musica
    id: f75f27a8-a2db-4f0c-bc66-2c57a57bcdbd
    type: content
  - name: Exclusive Interview with @AyeYoSmiley
    id: f8c3d3f3-5545-452b-929b-c0653e0af85f
    type: content
  - name: Politics
    id: 6e4f76bd-1873-403a-8674-63cf4c2e976e
    type: content
  - name: Community
    id: 6d348f24-814f-4f62-96a8-5ee97b3e255c
    type: content
  - name: Voces
    id: 0e36468d-e3a0-486b-8f13-7785504f7feb
    type: content
name: CHICA
author:
  email: vanessa@chica.io
  name: Vanessa Smith
  url: ''
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b37b3cd-17aa-443e-baa6-e15c394205ee.jpg
  appId: chicamag
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2bedeb6c-10b5-41f9-82bf-685b7a2f3048.png
