typography_spectrum: 0.17329399181271693
color:
  saturation: 0.8329952445846641
  brandStrength: 0.3674536238340569
  lightness: 0.25984712979193814
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  rhythmicContrast: 0.43352986456623466
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b37b3cd-17aa-443e-baa6-e15c394205ee.jpg
  appId: chicamag
layout_spectrum: 0.394768437060463
analytics:
  google: UA-96790026-1
author:
  email: vanessa@chica.io
  name: Vanessa Smith
  url: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2bedeb6c-10b5-41f9-82bf-685b7a2f3048.png
name: CHICA
navigation:
  - name: Musica
    id: f75f27a8-a2db-4f0c-bc66-2c57a57bcdbd
    type: content
  - name: Exclusive Interview with @AyeYoSmiley
    id: f8c3d3f3-5545-452b-929b-c0653e0af85f
    type: content
  - name: Politics
    id: 6e4f76bd-1873-403a-8674-63cf4c2e976e
    type: content
  - name: Community
    id: 6d348f24-814f-4f62-96a8-5ee97b3e255c
    type: content
  - name: Voces
    id: a380bc88-02d3-4dc9-8dab-ccc5bba879c2
    type: content
  - name: Voces
    id: 0e36468d-e3a0-486b-8f13-7785504f7feb
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Chica
content: []
description: Transforming the Narrative
purpose: []
