typography_spectrum: 0.5598924967925996
color:
  saturation: 0.1794392284937203
  brandStrength: 0.9869806782808155
  rhythmicContrast: 0.1450641960836947
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  lightness: 0.20499273715540767
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b37b3cd-17aa-443e-baa6-e15c394205ee.jpg
  appId: chicamag
layout_spectrum: 0.5699760979041457
author:
  email: vanessa@chica.io
  name: Vanessa Smith
  url: chica.io
logo: null
name: CHICA
navigation:
  - name: Musika
    id: f75f27a8-a2db-4f0c-bc66-2c57a57bcdbd
    type: content
  - name: Politics
    id: 6e4f76bd-1873-403a-8674-63cf4c2e976e
    type: content
  - name: Community
    id: 6d348f24-814f-4f62-96a8-5ee97b3e255c
    type: content
  - name: Voces
    id: 0e36468d-e3a0-486b-8f13-7785504f7feb
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Transforming the Narrative of Latinx
description: CHICA
purpose: []
