typography_spectrum: 0.5294404459797252
color:
  saturation: 0.5427669731499905
  brandStrength: 0.3391570135491836
  lightness: 0.11103931225568868
  brandColors:
    - '#F9FAE8'
    - '#053A5A'
    - '#EC578E'
    - '#6BC6BF'
    - '#6D4571'
  rhythmicContrast: 0.6147438226658667
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b37b3cd-17aa-443e-baa6-e15c394205ee.jpg
  appId: chicamag
layout_spectrum: 0.7302083472451103
analytics:
  google: UA-96790026-1
author:
  email: vanessa@chica.io
  name: Vanessa Smith
  url: 'http://chica.io'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2bedeb6c-10b5-41f9-82bf-685b7a2f3048.png
name: CHICA
url: 'https://chica.io'
navigation:
  - name: Musica
    id: f75f27a8-a2db-4f0c-bc66-2c57a57bcdbd
    type: content
  - name: Politics
    id: 6e4f76bd-1873-403a-8674-63cf4c2e976e
    type: content
  - name: Community
    id: 6d348f24-814f-4f62-96a8-5ee97b3e255c
    type: content
  - name: Voces
    id: a380bc88-02d3-4dc9-8dab-ccc5bba879c2
    type: content
  - name: Voces
    id: 0e36468d-e3a0-486b-8f13-7785504f7feb
    type: content
  - name: femenismo
    id: 6e1b1829-c56b-4d0b-9f4d-af06e80557fa
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Chica
content: []
description: Transforming the Narrative
purpose: []
