typography_spectrum: 0.09139781
color:
  saturation: 0.5427669731499905
  brandStrength: 0.9767025
  lightness: 0.1110393122556887
  brandColors:
    - '#F9FAE8'
    - '#053A5A'
    - '#EC578E'
    - '#6BC6BF'
    - '#6D4571'
  rhythmicContrast: 0.6147438226658667
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b37b3cd-17aa-443e-baa6-e15c394205ee.jpg
  appId: chicamag
layout_spectrum: 1
analytics:
  google: UA-96790026-1
author:
  email: vanessa@chica.io
  name: Vanessa Smith
  url: 'http://chica.io'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b0fc469b-ae58-44ae-967c-33017962fabd.png
name: Transforming the Narrative
url: 'https://chica.io'
navigation:
  - name: Musica
    id: f75f27a8-a2db-4f0c-bc66-2c57a57bcdbd
    type: content
  - name: Politics
    id: 6e4f76bd-1873-403a-8674-63cf4c2e976e
    type: content
  - name: Community
    id: 6d348f24-814f-4f62-96a8-5ee97b3e255c
    type: content
  - name: Voces
    id: 0e36468d-e3a0-486b-8f13-7785504f7feb
    type: content
  - name: femenismo
    id: 6e1b1829-c56b-4d0b-9f4d-af06e80557fa
    type: content
  - name: Cultura
    id: a380bc88-02d3-4dc9-8dab-ccc5bba879c2
    type: content
  - name: Música
    id: f8c3d3f3-5545-452b-929b-c0653e0af85f
    type: content
  - name: Loca Vibes
    id: 3468409f-bfef-4b94-9fc9-48482d06d498
    type: content
  - name: Voces
    id: 6c11972a-b34f-4a6a-b74a-b197443cf798
    type: content
  - name: 'Space, Earth & Technology'
    url: >-
      http://chica.io/detectan-un-sistema-estelar-cercano-con-siete-planetas-simil
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2972a49e-5f32-4c03-96dd-c77bcbc2ee6f.png
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Chica Magazine
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: audio
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fw.soundcloud.com%2Fplayer%2F%3Fvisual%3Dtrue%26url%3Dhttp%253A%252F%252Fapi.soundcloud.com%252Fplaylists%252F16213631%26show_artwork%3Dtrue&url=https%3A%2F%2Fsoundcloud.com%2Flocavibes%2Fsets%2Fchingonas&image=http%3A%2F%2Fi1.sndcdn.com%2Fartworks-000097194039-iwt4mk-t500x500.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=soundcloud"
      width="500" height="500" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: Loca Vibes Radio
          url: 'http://soundcloud.com/locavibes'
          avatar: {}
      related: []
      publisher:
        url: 'http://soundcloud.com'
        name: SoundCloud
        favicon: 'https://a-v2.sndcdn.com/assets/images/sc-icons/favicon-2cadd14b.ico'
        domain: soundcloud.com
      keywords:
        - record
        - sounds
        - share
        - sound
        - audio
        - tracks
        - music
        - soundcloud
      description: Musica de Xingonas pa Xingonas. Badass Woman music.
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      '@type': AudioObject
      app_links:
        - type: ios
          namespace: ai
          app_name: SoundCloud
          app_store_id: '336353151'
        - should_fallback: 'false'
          app_name: SoundCloud
          package: com.soundcloud.android
          url: 'soundcloud://playlists:16213631'
          namespace: ai
          type: ios
        - url: 'soundcloud://playlists:16213631'
          type: android
          namespace: ai
        - url: 'soundcloud://playlists:16213631'
          namespace: twitter
          type: ipad
          name: SoundCloud
          id: '336353151'
        - url: 'soundcloud://playlists:16213631'
          namespace: twitter
          type: iphone
          name: SoundCloud
          id: '336353151'
        - url: 'soundcloud://playlists:16213631'
          namespace: twitter
          type: googleplay
          name: SoundCloud
          id: com.soundcloud.android
        - path: 'soundcloud/playlists:16213631'
          package: com.soundcloud.android
          namespace: google
          type: android
        - path: 'soundcloud/playlists:16213631'
          package: '336353151'
          namespace: google
          type: ios
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://soundcloud.com/locavibes/sets/chingonas'
      title: XINGONAS by Loca Vibes Radio
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Transforming the Narrative
purpose: []
