title: Chica Magazine
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/984faf06-71a5-43f7-9e53-d2a0f7264ef1.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/984faf06-71a5-43f7-9e53-d2a0f7264ef1.png
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/309768ed-664e-4824-839b-5594807d70e0.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/309768ed-664e-4824-839b-5594807d70e0.jpg
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Transforming the Narrative
color:
  saturation: 0.5427669731499905
  brandStrength: 0.9767025
  rhythmicContrast: 0.6147438226658667
  brandColors:
    - '#F9FAE8'
    - '#053A5A'
    - '#EC578E'
    - '#6BC6BF'
    - '#6D4571'
  lightness: 0.1110393122556887
navigation:
  - name: Musica
    id: f75f27a8-a2db-4f0c-bc66-2c57a57bcdbd
    type: content
  - name: Politics
    id: 6e4f76bd-1873-403a-8674-63cf4c2e976e
    type: content
  - name: Community
    id: 6d348f24-814f-4f62-96a8-5ee97b3e255c
    type: content
  - name: Voces
    id: 0e36468d-e3a0-486b-8f13-7785504f7feb
    type: content
  - name: femenismo
    id: 6e1b1829-c56b-4d0b-9f4d-af06e80557fa
    type: content
  - name: Cultura
    id: a380bc88-02d3-4dc9-8dab-ccc5bba879c2
    type: content
  - name: Música
    id: f8c3d3f3-5545-452b-929b-c0653e0af85f
    type: content
  - name: Loca Vibes
    id: 3468409f-bfef-4b94-9fc9-48482d06d498
    type: content
  - name: Voces
    id: 6c11972a-b34f-4a6a-b74a-b197443cf798
    type: content
  - name: 'Space, Earth & Technology'
    url: >-
      http://chica.io/detectan-un-sistema-estelar-cercano-con-siete-planetas-simil
    type: external
analytics:
  google: UA-96790026-1
name: Transforming the Narrative
author:
  email: vanessa@chica.io
  name: Vanessa Smith
  url: 'http://chica.io'
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2972a49e-5f32-4c03-96dd-c77bcbc2ee6f.png
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b37b3cd-17aa-443e-baa6-e15c394205ee.jpg
  appId: chicamag
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b0fc469b-ae58-44ae-967c-33017962fabd.png
typography_spectrum: 0.09139781
layout_spectrum: 0.8548387
url: 'https://chica.io'
