title: Transforming the Narrative of Latinx
github: true
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
description: Transforming the Narrative of Latinx
color:
  saturation: 1
  brandStrength: 0.8340493
  rhythmicContrast: 1
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  lightness: 0.255102
navigation:
  - name: Musica
    id: f75f27a8-a2db-4f0c-bc66-2c57a57bcdbd
    type: content
  - name: Politics
    id: 6e4f76bd-1873-403a-8674-63cf4c2e976e
    type: content
  - name: Community
    id: 6d348f24-814f-4f62-96a8-5ee97b3e255c
    type: content
  - name: Voces
    id: 0e36468d-e3a0-486b-8f13-7785504f7feb
    type: content
name: CHICA
author:
  email: vanessa@chica.io
  name: Vanessa Smith
  url: chica.io
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b37b3cd-17aa-443e-baa6-e15c394205ee.jpg
  appId: chicamag
logo: null
typography_spectrum: 0.05699999793432653
layout_spectrum: 0.06928033
