layout_spectrum: 0.7385699048036212
typography_spectrum: 1
color:
  saturation: 0.5096970196988544
  brandStrength: 0.5233311667266569
  lightness: 0.3258195558999029
  brandColors:
    - '#000000'
    - '#333333'
    - '#FF358B'
    - '#01B0F0'
    - '#AEEE00'
  rhythmicContrast: 0.43128932767732087
title: 'Chicx '
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://s3-us-west-2.amazonaws.com/the-grid-img/p/37e51babe7085b7ad4967f13af471982f24eda39.png">
    src: >-
      https://s3-us-west-2.amazonaws.com/the-grid-img/p/37e51babe7085b7ad4967f13af471982f24eda39.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://s3-us-west-2.amazonaws.com'
        name: .s3-us-west-2.amazonaws.com
        favicon: null
        domain: s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
github: true
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: Transforming the Narrative of Latinx
navigation:
  - name: Musica
    id: f75f27a8-a2db-4f0c-bc66-2c57a57bcdbd
    type: content
  - name: Exclusive Interview with @AyeYoSmiley
    id: f8c3d3f3-5545-452b-929b-c0653e0af85f
    type: content
  - name: Politics
    id: 6e4f76bd-1873-403a-8674-63cf4c2e976e
    type: content
  - name: Community
    id: 6d348f24-814f-4f62-96a8-5ee97b3e255c
    type: content
  - name: Voces
    id: 0e36468d-e3a0-486b-8f13-7785504f7feb
    type: content
name: CHICA
author:
  email: vanessa@chica.io
  name: Vanessa Smith
  url: ''
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/3b37b3cd-17aa-443e-baa6-e15c394205ee.jpg
  appId: chicamag
logo: null
